apiVersion: v1
metadata:
  name: ovn-config
  namespace: ovn-kubernetes
  labels:
    app: ovn
data:
  OvnNorth: tcp://10.6.106.36:6641
  OvnSouth: tcp://10.6.106.36:6642
  k8s_apiserver: https://10.6.106.36:6443
  net_cidr: 10.244.0.0/16
  svc_cidr: 10.96.0.0/12
kind: ConfigMap
